config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :payments
    # post 'payments#create' 
    # get 'payments#success' 
    # get 'payments#cancel'
  root to: "home#index"
  
  devise_for :users

end

app/controllers/payment_controller.rb
class PaymentController < ApplicationController
	 def new
  end
  
  def create
    #create stripe customer for payment, update if already created
    customer = Stripe::Customer.create(
      name: current_user.full_name,
      email: current_user.email,
      description: "Customer id: #{current_user.id}",
    )
  
    session = Stripe::Checkout::Session.create( 
      customer: customer, 
      payment_method_types: [‘card’],
      line_items: [{
        price: 'price_1234', #price api id usually starts with price_ApIiD
        quantity: 1,
      }],
      mode: 'subscription',
      success_url:  payments_success_url,
      cancel_url: payments_cancel_url
     )
     redirect_to session.url
  end
  
  def success
    #handle successful payments
    redirect_to root_url, notice: "Purchase Successful"
  end
  
  def cancel
    #handle if the payment is cancelled
    redirect_to root_url, notice: "Purchase Unsuccessful"
  end
end

app/helpers/payment_helper.rb
module PaymentHelper
end

app/views/payment/new.html.erb
<%= form_tag payments_path do %>
  <label class="amount">
      <span>Amount: $5.00</span>
  </label>

  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="A month's subscription"
    data-amount="500"
    data-locale="auto">
  </script>
<% end %>